# Generated by Django 5.2.14 on 2026-06-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'contact queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlideConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_play_ms', models.PositiveIntegerField(default=4500)),
                ('slides', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'hero slide config',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('promo_code', models.CharField(blank=True, default='', max_length=50)),
                ('promo_discount', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_url2', models.URLField(blank=True, default='', max_length=500)),
                ('image_url3', models.URLField(blank=True, default='', max_length=500)),
                ('image_url4', models.URLField(blank=True, default='', max_length=500)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_icon', models.CharField(blank=True, default='lucide:box', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
                ('promo_code', models.CharField(blank=True, default='', max_length=50)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('service_type', models.CharField(max_length=100)),
                ('device_model', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Diagnosing', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_created', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jalaram Computers & IT Solutions', max_length=200)),
                ('addr1', models.CharField(default='Shop No. 5-7, Jalaram Arcade, Lamington Road', max_length=300)),
                ('addr2', models.CharField(default='Mumbai, Maharashtra - 400007', max_length=300)),
                ('gst', models.CharField(default='27AACJC2026P1Z3', max_length=50)),
                ('email', models.EmailField(default='jalaramcomputers21@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 98928 48643', max_length=30)),
                ('products_catalog_cleared', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('user_id_str', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default='Paid', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.JSONField(default=dict)),
                ('shipping_details', models.JSONField(blank=True, default=dict)),
                ('billing_details', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(default=list)),
                ('payment_method', models.CharField(blank=True, default='', max_length=200)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=200)),
                ('payment_gateway', models.CharField(blank=True, default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
