# Generated by Django 5.2.14 on 2026-06-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromo',
            fields=[
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
